name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths:
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@v2.0.0
        env:
          ANCHOR_EMAIL: ${{ wiromof299@wiemei.com }}
          ANCHOR_PASSWORD: ${{ Lamin!1234 }}
          EPISODE_PATH: /github/workspace
          SAVE_AS_DRAFT: true
          IS_EXPLICIT: true
          URL_IN_DESCRIPTION: true
